name: custom_detector
device: cuda
output_size: 5  # 4 for bbox + 1 for class
num_classes: 1  # Will be auto-updated based on dataset (number of classes discovered)
num_anchors: 6 #starting with 6 for now (accounts for different aspect ratios and scales of people in the images )
pretrained: true
transform:
  input_size: [640, 512] #no resizing 
confidence_threshold: 0.5
backbone:
  channels: [32, 64, 128]
  kernel_size: 3
  padding: 1
detector:
  hidden_size: 512
  dropout: 0.5
loss:
  cls_loss_weight: 0.5 
  box_loss_weight: ${eval:1 - model.loss.cls_loss_weight}

