#model:
name: faster_rcnn
device: cuda
transform:
  input_size: [480, 640]
  image_mean: [0.485, 0.456, 0.406]  # ImageNet RGB stats
  image_std: [0.229, 0.224, 0.225]
num_classes: 1  # Will be auto-updated based on dataset (number of classes discovered)
pretrained: false
backbone: mobilenet_v3_large_fpn
